import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

import Providers from "./Providers";
import { Page } from "@/components/Page";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Scala docs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning>
      <body className={plusJakartaSans.className}>
        <div className="min-h-screen">
          <Providers>
            <Page>{children}</Page>
          </Providers>
        </div>
      </body>
    </html>
  );
}
